# Generated by Django 2.2.1 on 2019-06-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='_datePosted',
            new_name='datePosted',
        ),
    ]
