# Generated by Django 2.2.1 on 2019-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(max_length=64)),
                ('itemNature', models.CharField(blank=True, default='Agricultural Item', max_length=32)),
                ('itemPrice', models.PositiveIntegerField(default=0)),
                ('totalItems', models.PositiveIntegerField(default=0)),
                ('isAvailable', models.BooleanField(default=False)),
                ('itemPosted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
