# Generated by Django 2.2.1 on 2019-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounteditem', '0002_auto_20190624_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounteditem',
            name='itemPrice',
            field=models.PositiveIntegerField(default=0, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='discounteditem',
            name='totalItems',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Items'),
        ),
    ]
