# Generated by Django 2.2.1 on 2019-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(default=None)),
                ('region', models.CharField(default='Punjab', max_length=128, verbose_name='Distribution Region')),
                ('experience', models.PositiveIntegerField()),
                ('dealsNature', models.CharField(max_length=128, verbose_name='Deal Nature')),
            ],
        ),
    ]
