# Generated by Django 2.2.1 on 2019-06-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=128, verbose_name='Item')),
                ('itemRate', models.PositiveIntegerField(default=0, verbose_name='Rate')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Total Quantity')),
                ('datePosted', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
            ],
        ),
    ]
